package org.iplantc.service.tags.domain;

import org.minnal.jpa.entity.BaseDomain;
import org.minnal.instrument.entity.Searchable;
import javax.persistence.Id;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.ManyToOne;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import com.fasterxml.jackson.annotation.JsonBackReference;
/**
 * Permission domain class
 *
 * @author Generated by minnal-generator
 */
// @Entity
// @Table(name="permissions")
public class Permission extends BaseDomain {

	@Searchable
	private String username;

	private String permission;

	private java.util.Date createdAt;

	private java.util.Date updatedAt;

	// @ManyToOne(fetch=FetchType.LAZY)
  // @JsonBackReference("permissions")
	// private Tag tag;
	//
	// @Id
	// @GeneratedValue(strategy=GenerationType.IDENTITY)
	// private Long id;
	//
	// /**
	//  * @return the id
	//  */
	// public Long getId() {
	// 	return id;
	// }
	//
	// /**
	//  * @param id the id to set
	//  */
	// public void setId(Long id) {
	// 	this.id = id;
	// }
	//
	// /**
	//  * @return the tag
	//  */
  // public Tag getTag() {
  // 	return this.tag;
  // }
	//
	// /**
	//  * @param tag the tag to set
	//  */
	// public void setTag(Tag tag) {
  // 	this.tag = tag;
  // }

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @return the permission
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * @return the createdAt
	 */
	public java.util.Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * @return the updatedAt
	 */
	public java.util.Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @param permission the permission to set
	 */
	public void setPermission(String permission) {
		this.permission = permission;
	}

	/**
	 * @param createdAt the createdAt to set
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * @param updatedAt the updatedAt to set
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
