package org.iplantc.service.tags.domain;

import org.minnal.jpa.entity.BaseDomain;
import org.minnal.instrument.entity.Searchable;
import javax.persistence.Id;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.AccessType;
import javax.persistence.Access;
import java.sql.Timestamp;

// import org.hibernate.validator.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Resource domain class
 *
 * @author Generated by minnal-generator
 */
@Entity
@Table(name="resources")
@Access(AccessType.FIELD)
public class Resource extends BaseDomain {

	@Searchable
	// @NotEmpty
	private String uuid;

	private Timestamp createdAt = new Timestamp(System.currentTimeMillis());

	private Timestamp updatedAt = new Timestamp(System.currentTimeMillis());

	@ManyToOne
  @JoinColumn(name = "tagId")
  @JsonBackReference("resources")
  private Tag tag;

	// @Id
	// @GeneratedValue(strategy=GenerationType.IDENTITY)
	// private Long id;
	//
	// /**
	//  * @return the id
	//  */
	// public Long getId() {
	// 	return id;
	// }
	//
	// /**
	//  * @param id the id to set
	//  */
	// public void setId(Long id) {
	// 	this.id = id;
	// }

	/**
	 * @return the tag
	 */
  public Tag getTag() {
  	return this.tag;
  }

	/**
	 * @param tag the tag to set
	 */
	public void setTag(Tag tag) {
  	this.tag = tag;
  }

	/**
	 * @return the uuid
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * @return the createdAt
	 */
	public Timestamp getCreatedAt() {
		return createdAt;
	}

	/**
	 * @return the updatedAt
	 */
	public Timestamp getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * @param uuid the uuid to set
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * @param createdAt the createdAt to set
	 */
	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * @param updatedAt the updatedAt to set
	 */
	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
